#!/usr/bin/env python3
"""Create improved version of 07_mlp_fundamentals.ipynb with all framework elements."""

import json
import copy
from pathlib import Path

def create_markdown_cell(content):
    """Create a markdown cell."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": content if isinstance(content, list) else [content]
    }

def create_code_cell(code):
    """Create a code cell."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": code if isinstance(code, list) else [code]
    }

# Load original notebook
nb_path = Path("notebooks/07_mlp_fundamentals.ipynb")
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Create improved notebook
improved_nb = copy.deepcopy(nb)
improved_nb['cells'] = []

# ==== 1. IMPROVED TITLE AND LEARNING OBJECTIVES ====
improved_nb['cells'].append(create_markdown_cell([
    "# 第7章: MLP（多層パーセプトロン）の基礎\n",
    "\n",
    "ニューラルネットワークの基本アーキテクチャを理解し、直感を養います。\n",
    "\n",
    "## 📋 この章で学ぶこと\n",
    "\n",
    "この章を終えると、以下ができるようになります：\n",
    "\n",
    "- [ ] MLPのアーキテクチャ（入力層、隠れ層、出力層）を理解し説明できる\n",
    "- [ ] 活性化関数（ReLU、Sigmoid、Tanh）の役割と特性を理解できる\n",
    "- [ ] scikit-learnを使ってMLPの分類器と回帰器を訓練できる\n",
    "- [ ] 損失曲線を読み取り、収束を判断できる\n",
    "- [ ] ハイパーパラメータ（層数、ニューロン数、学習率）の影響を理解できる\n",
    "- [ ] Early Stoppingを使って過学習を防げる\n",
    "\n",
    "## 🎯 前提知識\n",
    "\n",
    "この章を学ぶには以下の知識が必要です：\n",
    "\n",
    "- ✅ Python基礎（関数、ループ、リスト）\n",
    "- ✅ NumPy基礎（配列操作、基本演算）← Notebook 01で学習\n",
    "- ✅ データの前処理（StandardScaler）← Notebook 02で学習\n",
    "- ✅ モデル評価指標（正解率、RMSE、R²）← Notebook 03で学習\n",
    "- ✅ 機械学習の基本概念（訓練セット、テストセット、過学習）← Notebook 04-06で学習\n",
    "\n",
    "**必須ではないが役立つ知識：**\n",
    "- 線形代数の基礎（行列の掛け算）\n",
    "- 微分の基本（導関数の概念）\n",
    "\n",
    "⏱️ **推定学習時間**: 90-120分  \n",
    "📊 **難易度**: ★★★☆☆（中級）  \n",
    "🎓 **カテゴリ**: ニューラルネットワーク\n",
    "\n",
    "---\n"
]))

# ==== 2. MOTIVATION SECTION ====
improved_nb['cells'].append(create_markdown_cell([
    "## 💡 イントロダクション：なぜMLPを学ぶのか？\n",
    "\n",
    "### モチベーション\n",
    "\n",
    "**Q: なぜニューラルネットワークが重要なのか？**\n",
    "\n",
    "1. **万能近似定理**: MLPは理論的に任意の連続関数を近似できる\n",
    "2. **実世界での成功**: 画像認識、音声認識、自然言語処理で最先端の性能\n",
    "3. **Deep Learningの基礎**: より高度なネットワーク（CNN、RNN）の基盤\n",
    "\n",
    "### 🌍 実世界の応用例\n",
    "\n",
    "- **医療診断**: MRIスキャンから病気を検出\n",
    "- **金融**: 株価予測、不正検出\n",
    "- **製造業**: 製品の不良品検出\n",
    "- **マーケティング**: 顧客の行動予測\n",
    "\n",
    "### この章で作るもの\n",
    "\n",
    "- 様々なアーキテクチャのMLPを訓練\n",
    "- 決定境界を可視化して直感を養う\n",
    "- 最適なハイパーパラメータを見つける方法を学ぶ\n",
    "\n",
    "---\n"
]))

# ==== 3. ORIGINAL IMPORTS ====
improved_nb['cells'].append(nb['cells'][1])  # Import cell

# ==== 4. PART 1: ACTIVATION FUNCTIONS ====
improved_nb['cells'].append(nb['cells'][2])  # Part 1 title
improved_nb['cells'].append(nb['cells'][3])  # Activation functions code
improved_nb['cells'].append(nb['cells'][4])  # Visualization
improved_nb['cells'].append(nb['cells'][5])  # Comparison plot

# Add explanation after activation functions
improved_nb['cells'].append(create_markdown_cell([
    "### 💡 活性化関数の選び方\n",
    "\n",
    "| 活性化関数 | いつ使う？ | メリット | デメリット |\n",
    "|-----------|----------|---------|----------|\n",
    "| **ReLU** | 👍 **デフォルト（ほとんどの場合）** | 計算が速い、勾配消失問題なし | Dead neurons（ニューロンが死ぬ）|\n",
    "| **Tanh** | データが正規化されている場合 | 出力が-1～1でバランスが良い | 勾配消失問題あり |\n",
    "| **Sigmoid** | 出力層（二値分類の確率） | 0～1の確率として解釈可能 | 勾配消失問題あり |\n",
    "| **Leaky ReLU** | ReLUでDead neuronsが問題の時 | Dead neuronsを防ぐ | パラメータ調整が必要 |\n",
    "\n",
    "**👍 ベストプラクティス**: 迷ったらReLUを使う！\n",
    "\n",
    "---\n"
]))

# ==== 5. PART 2: MLP ARCHITECTURE ====
improved_nb['cells'].append(nb['cells'][6])  # Part 2 title
improved_nb['cells'].append(nb['cells'][7])  # Data generation
improved_nb['cells'].append(nb['cells'][8])  # Train simple MLP

# Add common errors section
improved_nb['cells'].append(create_markdown_cell([
    "### ⚠️ よくあるエラー #1: ConvergenceWarning\n",
    "\n",
    "上のセルを実行すると、以下のような警告が出る可能性があります：\n",
    "\n",
    "```\n",
    "ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached \n",
    "and the optimization hasn't converged yet.\n",
    "```\n",
    "\n",
    "**原因:**\n",
    "- イテレーション数（`max_iter`）が不足\n",
    "- 学習率が不適切（大きすぎる or 小さすぎる）\n",
    "- データがスケーリングされていない\n",
    "\n",
    "**✅ 解決法:**\n",
    "\n",
    "```python\n",
    "# ❌ 問題あり\n",
    "mlp = MLPClassifier(max_iter=100)  # 少なすぎる\n",
    "\n",
    "# ✅ 改善策1: イテレーション数を増やす\n",
    "mlp = MLPClassifier(max_iter=1000)\n",
    "\n",
    "# ✅ 改善策2: Early Stoppingを使う（推奨）\n",
    "mlp = MLPClassifier(max_iter=1000, early_stopping=True)\n",
    "\n",
    "# ✅ 改善策3: データを必ずスケーリング\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "scaler = StandardScaler()\n",
    "X_scaled = scaler.fit_transform(X)\n",
    "```\n",
    "\n",
    "---\n"
]))

improved_nb['cells'].append(nb['cells'][9])  # Weight examination

# ==== 6. PARTS 3-9: KEEP ORIGINAL CONTENT ====
for i in range(10, 26):
    improved_nb['cells'].append(nb['cells'][i])

# Add another common error section after Part 6
improved_nb['cells'].append(create_markdown_cell([
    "### ⚠️ よくあるエラー #2: データをスケーリングし忘れる\n",
    "\n",
    "**問題のあるコード:**\n",
    "\n",
    "```python\n",
    "# ❌ スケーリングなし\n",
    "mlp = MLPClassifier()\n",
    "mlp.fit(X_train, y_train)  # X_trainが生データ\n",
    "```\n",
    "\n",
    "**結果:**\n",
    "- 学習が遅い、または全く収束しない\n",
    "- 精度が低い\n",
    "- 損失曲線が不安定\n",
    "\n",
    "**✅ 正しいコード:**\n",
    "\n",
    "```python\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)  # 注意: fit_transformではなくtransform\n",
    "\n",
    "mlp = MLPClassifier()\n",
    "mlp.fit(X_train_scaled, y_train)\n",
    "```\n",
    "\n",
    "**重要**: テストセットには`transform()`のみ使用（`fit_transform()`ではない）！\n",
    "\n",
    "---\n"
]))

# ==== 7. PART 10: PRACTICAL TIPS ====
improved_nb['cells'].append(nb['cells'][26])  # Part 10 title
improved_nb['cells'].append(nb['cells'][27])  # Practical tips

# Add enhanced best practices
improved_nb['cells'].append(create_markdown_cell([
    "### 💡 実践的なベストプラクティス\n",
    "\n",
    "#### 🎯 アーキテクチャ設計の指針\n",
    "\n",
    "**開始点:**\n",
    "1. **小さく始める**: `hidden_layer_sizes=(50,)` から開始\n",
    "2. **必要に応じて拡大**: 精度が不十分なら層やニューロンを追加\n",
    "3. **ピラミッド構造**: `(100, 50, 25)` のように減少させる\n",
    "\n",
    "**層数の選び方:**\n",
    "- **1層**: 単純な非線形パターン\n",
    "- **2-3層**: ほとんどの実用的な問題\n",
    "- **4層以上**: 複雑な問題（ただし、scikit-learnより深層学習フレームワークを検討）\n",
    "\n",
    "#### ⚙️ ハイパーパラメータの推奨値\n",
    "\n",
    "```python\n",
    "# 推奨デフォルト設定\n",
    "mlp = MLPClassifier(\n",
    "    hidden_layer_sizes=(100, 50),      # 2層、ピラミッド構造\n",
    "    activation='relu',                 # ReLUがデフォルト\n",
    "    solver='adam',                     # Adamが最も汎用的\n",
    "    alpha=0.0001,                      # L2正則化（デフォルト）\n",
    "    learning_rate_init=0.001,          # Adamの推奨学習率\n",
    "    max_iter=1000,                     # 十分なイテレーション\n",
    "    early_stopping=True,               # 過学習防止\n",
    "    validation_fraction=0.1,           # 検証用に10%\n",
    "    n_iter_no_change=10,               # 10回改善なしで停止\n",
    "    random_state=42                    # 再現性のため\n",
    ")\n",
    "```\n",
    "\n",
    "#### 🔍 デバッグのコツ\n",
    "\n",
    "**学習がうまくいかない時のチェックリスト:**\n",
    "\n",
    "1. ✅ データをスケーリングしたか？\n",
    "2. ✅ 訓練セットとテストセットで同じscalerを使っているか？\n",
    "3. ✅ `max_iter`は十分か？\n",
    "4. ✅ 損失曲線を確認したか？（振動？収束？）\n",
    "5. ✅ クラスの不均衡はないか？\n",
    "\n",
    "**損失曲線の読み方:**\n",
    "- **右肩下がり**: ✅ 正常に学習中\n",
    "- **平坦**: 収束した or 学習率が小さすぎる\n",
    "- **振動**: 学習率が大きすぎる\n",
    "- **上昇**: 問題あり！学習率を下げる\n",
    "\n",
    "---\n"
]))

# ==== 8. SUMMARY (keep original) ====
improved_nb['cells'].append(nb['cells'][28])  # Summary

# ==== 9. SELF-ASSESSMENT QUIZ ====
improved_nb['cells'].append(create_markdown_cell([
    "---\n",
    "\n",
    "## 🎓 自己評価クイズ\n",
    "\n",
    "学習内容を確認しましょう！\n",
    "\n",
    "### Q1: MLPで最も重要な前処理は何ですか？\n",
    "\n",
    "<details>\n",
    "<summary>💡 答えを見る</summary>\n",
    "\n",
    "**答え**: 特徴量のスケーリング（StandardScalerなど）\n",
    "\n",
    "**理由**: ニューラルネットワークは特徴量のスケールに非常に敏感です。スケールが異なる特徴量があると：\n",
    "- 学習が遅くなる\n",
    "- 収束しない可能性がある\n",
    "- 一部の特徴量が過度に重視される\n",
    "\n",
    "</details>\n",
    "\n",
    "### Q2: ReLUの主な利点は何ですか？\n",
    "\n",
    "<details>\n",
    "<summary>💡 答えを見る</summary>\n",
    "\n",
    "**答え**: \n",
    "1. 計算が高速（max(0, x)だけ）\n",
    "2. 勾配消失問題がない（x > 0の場合、勾配=1）\n",
    "3. 実践的に優れた性能\n",
    "\n",
    "**欠点**: Dead neurons（一部のニューロンが常に0を出力し、学習しなくなる）\n",
    "\n",
    "</details>\n",
    "\n",
    "### Q3: Early Stoppingとは何ですか？なぜ使うのですか？\n",
    "\n",
    "<details>\n",
    "<summary>💡 答えを見る</summary>\n",
    "\n",
    "**答え**: 検証セットの性能が改善しなくなったら訓練を早期に停止する手法。\n",
    "\n",
    "**使う理由**:\n",
    "- 過学習を防ぐ\n",
    "- 訓練時間を節約\n",
    "- 最適なイテレーション数を自動で見つける\n",
    "\n",
    "**使い方**:\n",
    "```python\n",
    "mlp = MLPClassifier(early_stopping=True, validation_fraction=0.1, n_iter_no_change=10)\n",
    "```\n",
    "\n",
    "</details>\n",
    "\n",
    "### Q4: `hidden_layer_sizes=(100, 50)` は何を意味しますか？\n",
    "\n",
    "<details>\n",
    "<summary>💡 答えを見る</summary>\n",
    "\n",
    "**答え**: \n",
    "- 第1隠れ層: 100個のニューロン\n",
    "- 第2隠れ層: 50個のニューロン\n",
    "- 合計2つの隠れ層\n",
    "\n",
    "アーキテクチャ全体:\n",
    "```\n",
    "入力層(n_features) → 隠れ層1(100) → 隠れ層2(50) → 出力層(n_classes)\n",
    "```\n",
    "\n",
    "</details>\n",
    "\n",
    "### Q5: 損失曲線が振動している場合、どうすべきですか？\n",
    "\n",
    "<details>\n",
    "<summary>💡 答えを見る</summary>\n",
    "\n",
    "**答え**: 学習率（`learning_rate_init`）を下げる\n",
    "\n",
    "**対処法**:\n",
    "```python\n",
    "# 振動している場合\n",
    "mlp = MLPClassifier(learning_rate_init=0.0001)  # 0.001から0.0001に下げる\n",
    "```\n",
    "\n",
    "**逆に**、収束が遅すぎる場合は学習率を上げる。\n",
    "\n",
    "</details>\n",
    "\n",
    "---\n"
]))

# ==== 10. EXERCISES ====
improved_nb['cells'].append(create_markdown_cell([
    "## 🏋️ 演習問題\n",
    "\n",
    "実際に手を動かして理解を深めましょう！\n",
    "\n",
    "---\n"
]))

improved_nb['cells'].append(create_markdown_cell([
    "### 📝 基礎問題1: Circles データセットでMLPを訓練\n",
    "\n",
    "**課題**: `make_circles` データセットでMLPを訓練し、テスト精度0.90以上を達成してください。\n",
    "\n",
    "<details>\n",
    "<summary>💡 ヒント1</summary>\n",
    "\n",
    "- `make_circles`は2つの同心円のデータセット\n",
    "- 線形分離不可能なので、隠れ層が必要\n",
    "- まず`hidden_layer_sizes=(10,)`から試してみましょう\n",
    "\n",
    "</details>\n",
    "\n",
    "<details>\n",
    "<summary>💡 ヒント2</summary>\n",
    "\n",
    "- データのスケーリングを忘れずに！\n",
    "- `noise=0.1`で生成すると適度な難易度になります\n",
    "\n",
    "</details>\n",
    "\n",
    "<details>\n",
    "<summary>✅ 解答例</summary>\n",
    "\n",
    "```python\n",
    "from sklearn.datasets import make_circles\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "\n",
    "# データ生成\n",
    "X, y = make_circles(n_samples=1000, noise=0.1, random_state=42)\n",
    "\n",
    "# 分割\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "# スケーリング\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)\n",
    "\n",
    "# MLP訓練\n",
    "mlp = MLPClassifier(\n",
    "    hidden_layer_sizes=(20, 10),\n",
    "    activation='relu',\n",
    "    max_iter=1000,\n",
    "    random_state=42\n",
    ")\n",
    "mlp.fit(X_train_scaled, y_train)\n",
    "\n",
    "# 評価\n",
    "print(f\"Test Accuracy: {mlp.score(X_test_scaled, y_test):.4f}\")\n",
    "# 期待される出力: Test Accuracy: 0.9700以上\n",
    "```\n",
    "\n",
    "</details>\n"
]))

improved_nb['cells'].append(create_code_cell([
    "# ここにコードを書いてください\n",
    "\n"
]))

improved_nb['cells'].append(create_markdown_cell([
    "---\n",
    "\n",
    "### 📝 基礎問題2: 損失曲線の分析\n",
    "\n",
    "**課題**: 上で訓練したMLPの損失曲線をプロットし、収束を確認してください。\n",
    "\n",
    "<details>\n",
    "<summary>💡 ヒント</summary>\n",
    "\n",
    "- `mlp.loss_curve_`に損失の履歴が保存されています\n",
    "- `plt.plot()`で簡単にプロットできます\n",
    "\n",
    "</details>\n",
    "\n",
    "<details>\n",
    "<summary>✅ 解答例</summary>\n",
    "\n",
    "```python\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "plt.figure(figsize=(10, 5))\n",
    "plt.plot(mlp.loss_curve_)\n",
    "plt.xlabel('Iteration')\n",
    "plt.ylabel('Loss')\n",
    "plt.title('Training Loss Curve')\n",
    "plt.grid(True)\n",
    "plt.show()\n",
    "\n",
    "print(f\"Initial loss: {mlp.loss_curve_[0]:.4f}\")\n",
    "print(f\"Final loss: {mlp.loss_curve_[-1]:.4f}\")\n",
    "print(f\"Total iterations: {mlp.n_iter_}\")\n",
    "```\n",
    "\n",
    "</details>\n"
]))

improved_nb['cells'].append(create_code_cell([
    "# ここにコードを書いてください\n",
    "\n"
]))

improved_nb['cells'].append(create_markdown_cell([
    "---\n",
    "\n",
    "### 📝 応用問題: グリッドサーチで最適なハイパーパラメータを見つける\n",
    "\n",
    "**課題**: `GridSearchCV`を使って、`make_moons`データセットに対する最適なMLPハイパーパラメータを見つけてください。\n",
    "\n",
    "**探索するパラメータ:**\n",
    "- `hidden_layer_sizes`: `[(10,), (50,), (20, 10)]`\n",
    "- `alpha`: `[0.0001, 0.001, 0.01]`\n",
    "- `learning_rate_init`: `[0.001, 0.01]`\n",
    "\n",
    "<details>\n",
    "<summary>💡 ヒント</summary>\n",
    "\n",
    "- `GridSearchCV`は`sklearn.model_selection`からインポート\n",
    "- `cv=5`で5分割交差検証\n",
    "- `n_jobs=-1`で並列処理（高速化）\n",
    "\n",
    "</details>\n",
    "\n",
    "<details>\n",
    "<summary>✅ 解答例</summary>\n",
    "\n",
    "```python\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.datasets import make_moons\n",
    "\n",
    "# データ準備\n",
    "X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)\n",
    "\n",
    "# パラメータグリッド\n",
    "param_grid = {\n",
    "    'hidden_layer_sizes': [(10,), (50,), (20, 10)],\n",
    "    'alpha': [0.0001, 0.001, 0.01],\n",
    "    'learning_rate_init': [0.001, 0.01]\n",
    "}\n",
    "\n",
    "# グリッドサーチ\n",
    "mlp = MLPClassifier(max_iter=1000, random_state=42)\n",
    "grid_search = GridSearchCV(mlp, param_grid, cv=5, n_jobs=-1, verbose=1)\n",
    "grid_search.fit(X_train_scaled, y_train)\n",
    "\n",
    "# 結果\n",
    "print(\"Best parameters:\", grid_search.best_params_)\n",
    "print(f\"Best CV score: {grid_search.best_score_:.4f}\")\n",
    "print(f\"Test score: {grid_search.score(X_test_scaled, y_test):.4f}\")\n",
    "```\n",
    "\n",
    "</details>\n"
]))

improved_nb['cells'].append(create_code_cell([
    "# ここにコードを書いてください\n",
    "\n"
]))

improved_nb['cells'].append(create_markdown_cell([
    "---\n",
    "\n",
    "### 🔥 チャレンジ問題: 多クラス分類\n",
    "\n",
    "**課題**: `make_classification`で4クラスのデータセットを生成し、MLPで分類してください。混同行列とクラスごとの精度を表示してください。\n",
    "\n",
    "**要件:**\n",
    "- 4クラス（`n_classes=4`）\n",
    "- 特徴量20個（`n_features=20`）\n",
    "- サンプル数2000個\n",
    "- 全体精度0.80以上\n",
    "- 混同行列をヒートマップで可視化\n",
    "\n",
    "<details>\n",
    "<summary>💡 ヒント</summary>\n",
    "\n",
    "- `make_classification(n_classes=4, n_clusters_per_class=1)`\n",
    "- `confusion_matrix`は`sklearn.metrics`から\n",
    "- `sns.heatmap()`でヒートマップ表示\n",
    "- `classification_report`でクラスごとの詳細を表示\n",
    "\n",
    "</details>\n",
    "\n",
    "<details>\n",
    "<summary>✅ 解答例</summary>\n",
    "\n",
    "```python\n",
    "from sklearn.datasets import make_classification\n",
    "from sklearn.metrics import confusion_matrix, classification_report\n",
    "import seaborn as sns\n",
    "\n",
    "# データ生成\n",
    "X, y = make_classification(\n",
    "    n_samples=2000,\n",
    "    n_features=20,\n",
    "    n_informative=15,\n",
    "    n_classes=4,\n",
    "    n_clusters_per_class=1,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "# 分割・スケーリング\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)\n",
    "\n",
    "# MLP訓練\n",
    "mlp = MLPClassifier(\n",
    "    hidden_layer_sizes=(100, 50),\n",
    "    max_iter=1000,\n",
    "    early_stopping=True,\n",
    "    random_state=42\n",
    ")\n",
    "mlp.fit(X_train_scaled, y_train)\n",
    "\n",
    "# 予測\n",
    "y_pred = mlp.predict(X_test_scaled)\n",
    "\n",
    "# 混同行列\n",
    "cm = confusion_matrix(y_test, y_pred)\n",
    "plt.figure(figsize=(8, 6))\n",
    "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')\n",
    "plt.xlabel('Predicted')\n",
    "plt.ylabel('Actual')\n",
    "plt.title('Confusion Matrix')\n",
    "plt.show()\n",
    "\n",
    "# クラスごとの詳細\n",
    "print(classification_report(y_test, y_pred))\n",
    "print(f\"\\nOverall Accuracy: {mlp.score(X_test_scaled, y_test):.4f}\")\n",
    "```\n",
    "\n",
    "</details>\n"
]))

improved_nb['cells'].append(create_code_cell([
    "# ここにコードを書いてください\n",
    "\n"
]))

# ==== 11. COLUMN ====
improved_nb['cells'].append(create_markdown_cell([
    "---\n",
    "\n",
    "## 📖 コラム: 万能近似定理とは？\n",
    "\n",
    "### 理論的背景\n",
    "\n",
    "1989年、George Cybenkoは驚くべき定理を証明しました：\n",
    "\n",
    "> **万能近似定理**: 十分な数のニューロンを持つ1層の隠れ層を持つニューラルネットワークは、  \n",
    "> 任意の連続関数を任意の精度で近似できる。\n",
    "\n",
    "### これは何を意味するのか？\n",
    "\n",
    "理論的には、`hidden_layer_sizes=(10000,)` のような単層の巨大なネットワークで  \n",
    "あらゆる関数を近似できます。\n",
    "\n",
    "### しかし、実際には...\n",
    "\n",
    "**問題:**\n",
    "- 「近似できる」≠「効率的に学習できる」\n",
    "- 単層では必要なニューロン数が膨大になる\n",
    "- 訓練に時間がかかりすぎる\n",
    "\n",
    "**解決策: 深いネットワーク**\n",
    "- 多層（深い）ネットワークは、より少ないパラメータで複雑な関数を表現可能\n",
    "- 例: `(100, 50, 25)` は `(1000,)` より効率的なことが多い\n",
    "\n",
    "これが**Deep Learning**（深層学習）の理論的基礎です！\n",
    "\n",
    "### 実験で確認\n",
    "\n",
    "同じ性能を達成するのに：\n",
    "- 単層: `(500,)` → 約10,000パラメータ\n",
    "- 多層: `(50, 25, 10)` → 約2,000パラメータ\n",
    "\n",
    "**結論**: 深いネットワークの方が効率的！\n",
    "\n",
    "### 参考文献\n",
    "- Cybenko, G. (1989) \"Approximation by superpositions of a sigmoidal function\"\n",
    "- Hornik, K. (1991) \"Approximation capabilities of multilayer feedforward networks\"\n",
    "\n",
    "---\n"
]))

# ==== 12. PROGRESS TRACKING ====
improved_nb['cells'].append(create_markdown_cell([
    "## 🎯 学習進捗の記録\n",
    "\n",
    "この章を完了したら、以下のセルを実行して進捗を記録しましょう！\n"
]))

improved_nb['cells'].append(create_code_cell([
    "# 🎯 進捗管理システム\n",
    "import json\n",
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "\n",
    "def mark_complete(notebook_number, notebook_name):\n",
    "    \"\"\"このノートブックを完了済みにマーク\"\"\"\n",
    "    progress_file = Path(\"../learning_progress.json\")\n",
    "    \n",
    "    # Load existing progress\n",
    "    if progress_file.exists():\n",
    "        with open(progress_file, 'r') as f:\n",
    "            progress = json.load(f)\n",
    "    else:\n",
    "        progress = {\"completed\": [], \"timestamps\": {}}\n",
    "    \n",
    "    # Mark as complete\n",
    "    if notebook_number not in progress[\"completed\"]:\n",
    "        progress[\"completed\"].append(notebook_number)\n",
    "        progress[\"completed\"].sort()\n",
    "        progress[\"timestamps\"][str(notebook_number)] = datetime.now().isoformat()\n",
    "    \n",
    "    # Save\n",
    "    with open(progress_file, 'w') as f:\n",
    "        json.dump(progress, f, indent=2)\n",
    "    \n",
    "    # Display progress\n",
    "    total_notebooks = 13\n",
    "    completion_rate = len(progress[\"completed\"]) / total_notebooks * 100\n",
    "    \n",
    "    print(f\"\\n{'='*60}\")\n",
    "    print(f\"🎉 Notebook {notebook_number:02d}: {notebook_name} 完了！\")\n",
    "    print(f\"{'='*60}\")\n",
    "    print(f\"\\n📊 全体進捗: {completion_rate:.1f}% ({len(progress['completed'])}/{total_notebooks})\")\n",
    "    \n",
    "    # Progress bar\n",
    "    bar_length = 40\n",
    "    filled = int(bar_length * completion_rate / 100)\n",
    "    bar = '█' * filled + '░' * (bar_length - filled)\n",
    "    print(f\"\\n[{bar}] {completion_rate:.0f}%\\n\")\n",
    "    \n",
    "    # Badges\n",
    "    if completion_rate >= 25 and completion_rate < 50:\n",
    "        print(\"🏆 バッジ獲得: ビギナー（25%達成）\")\n",
    "    elif completion_rate >= 50 and completion_rate < 75:\n",
    "        print(\"🏆 バッジ獲得: 中級者（50%達成）\")\n",
    "    elif completion_rate >= 75 and completion_rate < 100:\n",
    "        print(\"🏆 バッジ獲得: 上級者（75%達成）\")\n",
    "    elif completion_rate >= 100:\n",
    "        print(\"🎓 バッジ獲得: マスター（100%達成）\")\n",
    "        print(\"\\n✨ おめでとうございます！全ノートブックを完了しました！ ✨\")\n",
    "    \n",
    "    # Next notebook\n",
    "    if notebook_number < total_notebooks:\n",
    "        print(f\"\\n➡️  次のノートブック: Notebook {notebook_number+1:02d}\")\n",
    "    \n",
    "    print(f\"\\n{'='*60}\\n\")\n",
    "\n",
    "# このノートブックを完了したら以下のコメントを外して実行\n",
    "# mark_complete(7, \"MLP Fundamentals\")"
]))

# ==== 13. FINAL NEXT STEPS ====
improved_nb['cells'].append(create_markdown_cell([
    "---\n",
    "\n",
    "## ➡️ 次のステップ\n",
    "\n",
    "### 学習を続ける\n",
    "\n",
    "MLPの基礎を理解したら、次は：\n",
    "\n",
    "**📗 Notebook 08: MLP Parameter Space Exploration**\n",
    "- より広範なハイパーパラメータ探索\n",
    "- ヒートマップでパラメータの影響を可視化\n",
    "- 最適化戦略の理解\n",
    "\n",
    "### 復習が必要な場合\n",
    "\n",
    "- **Notebook 02**: 前処理とスケーリングを復習\n",
    "- **Notebook 03**: 評価指標を復習\n",
    "- **Notebook 04-06**: 他のアルゴリズムと比較\n",
    "\n",
    "### さらに学ぶために\n",
    "\n",
    "**書籍:**\n",
    "- \"Neural Networks and Deep Learning\" by Michael Nielsen（無料オンライン）\n",
    "- \"Deep Learning\" by Goodfellow, Bengio, and Courville\n",
    "\n",
    "**オンラインコース:**\n",
    "- Coursera: \"Neural Networks and Deep Learning\" by Andrew Ng\n",
    "- Fast.ai: \"Practical Deep Learning for Coders\"\n",
    "\n",
    "**実践:**\n",
    "- Kaggle competitions で実データに挑戦\n",
    "- UCI ML Repository のデータセットで練習\n",
    "\n",
    "---\n",
    "\n",
    "### 🎉 お疲れ様でした！\n",
    "\n",
    "この章で学んだMLPの知識は、Deep Learningへの第一歩です。  \n",
    "次の章でさらに深く探求しましょう！\n"
]))

# Save improved notebook
output_path = Path("notebooks/07_mlp_fundamentals_improved.ipynb")
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(improved_nb, f, indent=1, ensure_ascii=False)

print(f"✅ Improved notebook created: {output_path}")
print(f"📊 Total cells: {len(improved_nb['cells'])}")
print(f"📈 Original cells: {len(nb['cells'])}")
print(f"➕ Added cells: {len(improved_nb['cells']) - len(nb['cells'])}")
